### ISSUE TITLE
AnsibleUndefinedVariable: 'path_based_cell_url_enabled' is undefined

### ISSUE THREAD

**Issue by tochi-y** [personium/setup-vagrant#49]
vagrant up failed due to the following error.

```
    default: TASK [Deploy personium-config.properties] **************************************
    default: fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'path_based_cell_url_enabled' is undefined"}
    default: 
    default: PLAY RECAP *********************************************************************
    default: 127.0.0.1                  : ok=202  changed=166  unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
    default: Mon Jun 29 07:48:37 UTC 2020
```

host file should be updated to the latest host file. 
https://github.com/personium/ansible/blob/develop/1-server_unit/static_inventory/hosts
